package com.auth.pojo;

// default package
// Generated 2014-3-24 18:52:51 by Hibernate Tools 4.0.0

/**
 * CarInformation generated by hbm2java
 */
public class CarInformation implements java.io.Serializable {

	private Integer id;
	private Driver driver;
	private String numcode;
	private String carstatus;
	private String carnum;
	private String cartype;
	private String brand;
	private String carmodel;
	private String carcolor;
	private String identify;
	private String enginenum;
	private String buydate;
	private String regdate;
	private String memo;

	public CarInformation() {
	}

	public CarInformation(Driver driver, String numcode, String carstatus,
			String carnum, String cartype, String brand, String carmodel,
			String carcolor, String identify, String enginenum, String buydate,
			String regdate, String memo) {
		this.driver = driver;
		this.numcode = numcode;
		this.carstatus = carstatus;
		this.carnum = carnum;
		this.cartype = cartype;
		this.brand = brand;
		this.carmodel = carmodel;
		this.carcolor = carcolor;
		this.identify = identify;
		this.enginenum = enginenum;
		this.buydate = buydate;
		this.regdate = regdate;
		this.memo = memo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Driver getDriver() {
		return this.driver;
	}

	public void setDriver(Driver driver) {
		this.driver = driver;
	}

	public String getNumcode() {
		return this.numcode;
	}

	public void setNumcode(String numcode) {
		this.numcode = numcode;
	}

	public String getCarstatus() {
		return this.carstatus;
	}

	public void setCarstatus(String carstatus) {
		this.carstatus = carstatus;
	}

	public String getCarnum() {
		return this.carnum;
	}

	public void setCarnum(String carnum) {
		this.carnum = carnum;
	}

	public String getCartype() {
		return this.cartype;
	}

	public void setCartype(String cartype) {
		this.cartype = cartype;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getCarmodel() {
		return this.carmodel;
	}

	public void setCarmodel(String carmodel) {
		this.carmodel = carmodel;
	}

	public String getCarcolor() {
		return this.carcolor;
	}

	public void setCarcolor(String carcolor) {
		this.carcolor = carcolor;
	}

	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	public String getEnginenum() {
		return this.enginenum;
	}

	public void setEnginenum(String enginenum) {
		this.enginenum = enginenum;
	}

	public String getBuydate() {
		return this.buydate;
	}

	public void setBuydate(String buydate) {
		this.buydate = buydate;
	}

	public String getRegdate() {
		return this.regdate;
	}

	public void setRegdate(String regdate) {
		this.regdate = regdate;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
