package com.auth.pojo;

// default package
// Generated 2014-3-24 18:52:51 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer id;
	private Integer sequence;
	private String menuname;
	private String linkaddress;
	private Set roleMenus = new HashSet(0);

	public Menu() {
	}

	public Menu(Integer sequence, String menuname, String linkaddress,
			Set roleMenus) {
		this.sequence = sequence;
		this.menuname = menuname;
		this.linkaddress = linkaddress;
		this.roleMenus = roleMenus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	public String getMenuname() {
		return this.menuname;
	}

	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}

	public String getLinkaddress() {
		return this.linkaddress;
	}

	public void setLinkaddress(String linkaddress) {
		this.linkaddress = linkaddress;
	}

	public Set getRoleMenus() {
		return this.roleMenus;
	}

	public void setRoleMenus(Set roleMenus) {
		this.roleMenus = roleMenus;
	}

}
