package com.auth.pojo;

// default package
// Generated 2014-3-24 18:52:51 by Hibernate Tools 4.0.0

/**
 * Rescueapply generated by hbm2java
 */
public class Rescueapply implements java.io.Serializable {

	private Integer id;
	private String applytime;
	private String enteringtime;
	private String applyperson;
	private String casenum;
	private String applyphone;
	private String accidentcause;
	private String rescueaddr;
	private String carnum;
	private String motorcycle;
	private String carcolor;
	private String destination;
	private String destinationtype;
	private Float estimatedcost;
	private String memo;
	private String status;
	private String scheduleperson;
	private String dispatchnum;
	private String dispatchtime;
	private String rescuecar;
	private String driver;
	private String driverphone;
	private String rescuememo;
	private String returntime;
	private String mileage;
	private Float realcost;
	private Float incomebalance;
	private Float finalcost;
	private String returmemo;
	private String paytype;
	private String ifpay;

	public Rescueapply() {
	}

	public Rescueapply(String applytime, String enteringtime,
			String applyperson, String casenum, String applyphone,
			String accidentcause, String rescueaddr, String carnum,
			String motorcycle, String carcolor, String destination,
			String destinationtype, Float estimatedcost, String memo,
			String status, String scheduleperson, String dispatchnum,
			String dispatchtime, String rescuecar, String driver,
			String driverphone, String rescuememo, String returntime,
			String mileage, Float realcost, Float incomebalance,
			Float finalcost, String returmemo, String paytype, String ifpay) {
		this.applytime = applytime;
		this.enteringtime = enteringtime;
		this.applyperson = applyperson;
		this.casenum = casenum;
		this.applyphone = applyphone;
		this.accidentcause = accidentcause;
		this.rescueaddr = rescueaddr;
		this.carnum = carnum;
		this.motorcycle = motorcycle;
		this.carcolor = carcolor;
		this.destination = destination;
		this.destinationtype = destinationtype;
		this.estimatedcost = estimatedcost;
		this.memo = memo;
		this.status = status;
		this.scheduleperson = scheduleperson;
		this.dispatchnum = dispatchnum;
		this.dispatchtime = dispatchtime;
		this.rescuecar = rescuecar;
		this.driver = driver;
		this.driverphone = driverphone;
		this.rescuememo = rescuememo;
		this.returntime = returntime;
		this.mileage = mileage;
		this.realcost = realcost;
		this.incomebalance = incomebalance;
		this.finalcost = finalcost;
		this.returmemo = returmemo;
		this.paytype = paytype;
		this.ifpay = ifpay;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getApplytime() {
		return this.applytime;
	}

	public void setApplytime(String applytime) {
		this.applytime = applytime;
	}

	public String getEnteringtime() {
		return this.enteringtime;
	}

	public void setEnteringtime(String enteringtime) {
		this.enteringtime = enteringtime;
	}

	public String getApplyperson() {
		return this.applyperson;
	}

	public void setApplyperson(String applyperson) {
		this.applyperson = applyperson;
	}

	public String getCasenum() {
		return this.casenum;
	}

	public void setCasenum(String casenum) {
		this.casenum = casenum;
	}

	public String getApplyphone() {
		return this.applyphone;
	}

	public void setApplyphone(String applyphone) {
		this.applyphone = applyphone;
	}

	public String getAccidentcause() {
		return this.accidentcause;
	}

	public void setAccidentcause(String accidentcause) {
		this.accidentcause = accidentcause;
	}

	public String getRescueaddr() {
		return this.rescueaddr;
	}

	public void setRescueaddr(String rescueaddr) {
		this.rescueaddr = rescueaddr;
	}

	public String getCarnum() {
		return this.carnum;
	}

	public void setCarnum(String carnum) {
		this.carnum = carnum;
	}

	public String getMotorcycle() {
		return this.motorcycle;
	}

	public void setMotorcycle(String motorcycle) {
		this.motorcycle = motorcycle;
	}

	public String getCarcolor() {
		return this.carcolor;
	}

	public void setCarcolor(String carcolor) {
		this.carcolor = carcolor;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getDestinationtype() {
		return this.destinationtype;
	}

	public void setDestinationtype(String destinationtype) {
		this.destinationtype = destinationtype;
	}

	public Float getEstimatedcost() {
		return this.estimatedcost;
	}

	public void setEstimatedcost(Float estimatedcost) {
		this.estimatedcost = estimatedcost;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getScheduleperson() {
		return this.scheduleperson;
	}

	public void setScheduleperson(String scheduleperson) {
		this.scheduleperson = scheduleperson;
	}

	public String getDispatchnum() {
		return this.dispatchnum;
	}

	public void setDispatchnum(String dispatchnum) {
		this.dispatchnum = dispatchnum;
	}

	public String getDispatchtime() {
		return this.dispatchtime;
	}

	public void setDispatchtime(String dispatchtime) {
		this.dispatchtime = dispatchtime;
	}

	public String getRescuecar() {
		return this.rescuecar;
	}

	public void setRescuecar(String rescuecar) {
		this.rescuecar = rescuecar;
	}

	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	public String getDriverphone() {
		return this.driverphone;
	}

	public void setDriverphone(String driverphone) {
		this.driverphone = driverphone;
	}

	public String getRescuememo() {
		return this.rescuememo;
	}

	public void setRescuememo(String rescuememo) {
		this.rescuememo = rescuememo;
	}

	public String getReturntime() {
		return this.returntime;
	}

	public void setReturntime(String returntime) {
		this.returntime = returntime;
	}

	public String getMileage() {
		return this.mileage;
	}

	public void setMileage(String mileage) {
		this.mileage = mileage;
	}

	public Float getRealcost() {
		return this.realcost;
	}

	public void setRealcost(Float realcost) {
		this.realcost = realcost;
	}

	public Float getIncomebalance() {
		return this.incomebalance;
	}

	public void setIncomebalance(Float incomebalance) {
		this.incomebalance = incomebalance;
	}

	public Float getFinalcost() {
		return this.finalcost;
	}

	public void setFinalcost(Float finalcost) {
		this.finalcost = finalcost;
	}

	public String getReturmemo() {
		return this.returmemo;
	}

	public void setReturmemo(String returmemo) {
		this.returmemo = returmemo;
	}

	public String getPaytype() {
		return this.paytype;
	}

	public void setPaytype(String paytype) {
		this.paytype = paytype;
	}

	public String getIfpay() {
		return this.ifpay;
	}

	public void setIfpay(String ifpay) {
		this.ifpay = ifpay;
	}

}
