package com.auth.pojo;

// default package
// Generated 2014-3-24 18:52:51 by Hibernate Tools 4.0.0

/**
 * RoleMenu generated by hbm2java
 */
public class RoleMenu implements java.io.Serializable {

	private Integer id;
	private Role role;
	private Menu menu;

	public RoleMenu() {
	}

	public RoleMenu(Role role, Menu menu) {
		this.role = role;
		this.menu = menu;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

}
